import { IEducation } from '../IEducation';
import { IEmail } from '../IEmail';
import { IExperience } from '../IExperience';
import { ILoc } from '../ILoc';
import { ICompanyLocation } from '../ICompanyLocation';
import { StringArrayOrEmptyArray } from '../../custom_types/UnlockedStatus';

export interface IPDLSource {
  birth_date: string;
  birth_year: number;
  certifications: string[];
  countries: string[];
  education: IEducation[];
  email?: string;
  emails: IEmail[];
  enriched_emails: string[];
  enriched_phone: string[];
  experience: IExperience[];
  facebook_id: string;
  facebook_url: string;
  facebook_username: string;
  first_name: string;
  flag: boolean;
  full_name: string;
  gender: string;
  github_url: string;
  github_username: string;
  id: string;
  industry: string;
  inferred_salary: string;
  inferred_years_experience: number;
  interests: StringArrayOrEmptyArray;
  job_company_facebook_url: string;
  job_company_founded: string;
  job_company_id: string;
  job_company_industry: string;
  job_company_linkedin_id: string;
  job_company_linkedin_url: string;
  job_company_location_address_line_2: string;
  job_company_location_continent: string;
  job_company_location_country: string;
  job_company_location_geo: string;
  job_company_location_locality: string;
  job_company_location_metro: string;
  job_company_location_name: string;
  job_company_location_postal_code: string;
  job_company_location_region: string;
  job_company_location_street_address: string;
  job_company_name: string;
  job_company_size: string;
  job_company_twitter_url: string;
  job_company_website: string;
  job_last_updated: string;
  job_start_date: string;
  job_summary: string;
  job_title: string;
  job_title_levels: [];
  job_title_role: string;
  job_title_sub_role: string;
  languages: StringArrayOrEmptyArray;
  last_initial: string;
  last_name: string;
  linkedin_connections: number;
  linkedin_id: number;
  linkedin_url: string;
  linkedin_username: string;
  location_address_line_2: string;
  location_continent: string;
  location_country: string;
  location_geo: string;
  location_last_updated: string;
  location_locality: string;
  location_metro: string;
  location_name: string;
  location_names: string[];
  location_postal_code: string;
  location_region: string;
  location_street_address: string;
  middle_initial: string;
  middle_name: string;
  mobile_phone: string;
  myloc: ILoc;
  operation_id: string;
  personal_emails: string[];
  phone_number?: string;
  phone_numbers: string[];
  profiles: IShortProfile[];
  regions: string[];
  response?: any;
  resume_content?: string;
  resume_loaded?: boolean;
  skills: string[];
  street_addresses: ICompanyLocation[];
  summary: string;
  twitter_url: string;
  twitter_username: string;
  updated_on?: string;
  version_status: IVersionStatus;
  work_email: string;
}

interface IShortProfile {
  id: string;
  network: string;
  url: string;
  username: string;
}
interface IVersionStatus {
  contains: [];
  current_version: string;
  previous_version: string;
  status: 'updated' | string;
}
